replicaCount: 1

image:
  repository: faizan00parvez/deploywatch
  tag: 4ec539e78907c78101214743650857912223d481
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70