replicaCount: 1

image:
  repository: faizan00parvez/deploywatch
  tag: c1ef1a25bffc324442162fb2c01ff1a128da2a8a
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70